spring.application.name=PaymentService
spring.profiles.active=docker

internal.secret=super-secret-internal
internal.secret.header=X-Internal-Secret

services.random.url=https://api.random.org/json-rpc/4/invoke
services.random.number.min=1
services.random.number.max=100
services.random.number.base=10
services.random.number.amount=1
services.random.api.method=generateIntegers
services.random.api.key=ef47a4da-232d-4363-bc16-d241effba0aa

mongock.migration-scan-package=com.innowise.paymentservice.db.migration
mongock.enabled=true