spring.application.name=PaymentService
spring.profiles.active=docker

internal.secret=super-secret-internal
internal.secret.header=X-Internal-Secret

service.random.url=https://api.random.org/json-rpc/4/invoke
service.random.number.min=1
service.random.number.max=100
service.random.number.base=10
service.random.number.amount=1
service.random.api.method=generateIntegers
service.random.api.key=ef47a4da-232d-4363-bc16-d241effba0aa